Created spring web config and one page
YuraMitriakhin/hibernate pull request #7
Opened 2021-02-11 12:30 UTC by YuraMitriakhin

2021-02-11 12:38 UTC, Artificial-Friend approved these changes
Gj!

2021-02-11 14:11 UTC, Sofasmile requested changes

2021-02-11 14:11 UTC, Sofasmile commented on src/main/java/com/gmail/yuramitryahin/model/CinemaHall.java
> +@Component
should an entity be bean?

2021-02-11 18:44 UTC, YuraMitriakhin commented on src/main/java/com/gmail/yuramitryahin/model/CinemaHall.java
> +@Component
maybe no

2021-02-12 07:23 UTC, Sofasmile approved these changes

2021-02-12 07:26 UTC, Sofasmile commented on src/main/java/com/gmail/yuramitryahin/model/CinemaHall.java
> +@Component
наші модельки (ентіті) не повинні бути бінами. Адже ми їх ніде не інжектимо. І загалом, нам не доцільно мати лише один об'єкт модельки, який буде управлятись спрінгом. Протягом роботи програми ми будемо створювати безліч екземплярів цих класів. 
А якщо ми говоримо про сервіси чи репозиторії - то нам достатньо 1 об'єкта, який буде виконувати потрібну логіку. Тому ми ставимо над класом відповідну антацію і віддаємо управління спрінгу

2021-02-12 10:48 UTC, YuraMitriakhin commented on src/main/java/com/gmail/yuramitryahin/model/CinemaHall.java
> +@Component
зрозуміло)

2021-02-12 10:48 UTC, merged